### ISSUE TITLE
High TPS due to /balance.

### ISSUE THREAD

**Issue by TrademarkTM** [AppleDash/SaneEconomy#25] opened 2016-12-10 12:16 UTC
Hello guys.
I was in my server and used /money pay. Obviously it doesn't work. But then it processed the command, and took about 2 seconds to send me that there's no account called "pay". But the problem is that it causes huge lag to tell me that.

Maybe just make it async? It freezes the server for a while, even if my database (flatfile) is totally clear.

Timings:
http://prntscr.com/dhnvnc

**Comment by AppleDash** [comment] 2016-12-10 13:26
Are you able to reproduce this more than once?

**Comment by TrademarkTM** [comment] 2016-12-10 15:33
Everytime I use /money [username] the TPS drop occours.
It have to be with a new username - e.g. random numbers/characters.

**Comment by AppleDash** [comment] 2016-12-10 15:37
Thanks a bunch, looking into it now!

**Comment by AppleDash** [comment] 2016-12-10 15:43
I can't reproduce this under a profiler. What other plugins are you running, and what version of SaneEco @TrademarkTM

**Comment by TrademarkTM** [comment] 2016-12-10 17:38
Lastest version (downloaded today).
http://prntscr.com/dhrc8e - my plugins

There are no scripts running.
This is a local server, so the database has exactly one player (me).

**Comment by AppleDash** [comment] 2016-12-10 17:52
I understand the issue - the issue is that whenever it tries to look up a player, it hits the Mojang API to try and figure out if that player actually exists, and retrieve their UUID and such. You have a slow Internet connection, so every API request takes a couple of seconds which freezes your server. I'll look into some way of making this work a bit better.

**Comment by TrademarkTM** [comment] 2016-12-10 18:05
Yes, my internet is kinda poor.
But shouldn't it be an async task? Some trolls may spam these commands with bots or something and lag my server, even if they're in a host.

**Comment by AppleDash** [comment] 2016-12-11 18:18
Like I said, looking into it.

**Comment by AppleDash** [comment] 2016-12-15 22:48
Expect an update that fixes this issue within a couple of days :)

**Comment by AppleDash** [comment] 2016-12-16 01:28
Will be fixed in 0.10.0. Currently testing it, not yet released, but the plugin will notify you to update when it is!

**Comment by TrademarkTM** [comment] 2016-12-16 17:53
Ok, thank you!
You're an amazing developer.

**Comment by MGAndreasen** [comment] 2017-01-03 21:38
Could we not just make an extra table in sql, with UUID, playername and revalidate the playername once per session or something, and then use that table for lookups, it will also make some of the sql easier i think.

update <whatEverTable> set <field> = <field>+10 where playername = '<playername>'

or simply with a uuid, playername table for fetching the player name or joining the tables together.

**Comment by AppleDash** [comment] 2017-01-17 13:23
Try 0.10.1.

**Closed as completed by AppleDash** 2017-01-17 13:23 UTC
